const mongoose = require('mongoose')

/**
 * Certificate — generated by admin for a user based on their badge achievement.
 * Stored as a base64 PNG (or URL if hosted externally in the future).
 */
const certificateSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    badgeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Badge' },
    tier: {
      type: String,
      enum: ['codespark', 'codeflame', 'codeelite'],
      required: true,
    },
    badgeName: { type: String, required: true }, // e.g. "CodeElite"
    month: { type: Number, required: true },
    year: { type: Number, required: true },
    resourceCount: { type: Number, default: 0 },
    issuedByAdmin: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    /** base64-encoded PNG image of the certificate */
    imageData: { type: String, required: true },
    /** Has the user downloaded it? */
    downloaded: { type: Boolean, default: false },
  },
  { timestamps: true }
)

// One certificate per user per tier per month
certificateSchema.index({ userId: 1, tier: 1, month: 1, year: 1 }, { unique: true })

module.exports = mongoose.model('Certificate', certificateSchema)
